export const IncidentType = {
  TRAFFIC: 'TRANSITO',
  MECHANICAL_FAILURE: 'FALLA_MECANICA',
  FLAT_TIRE: 'PINCHADURA',
  REFUELING: 'CARGA_DE_COMBUSTIBLE',
  ROAD_CLOSURE: 'CORTE_DE_CALLE',
  ACCIDENT: 'ACCIDENTE',
  WEATHER: 'PROBLEMA_CLIMATICO',
  DRIVER_DELAY: 'DEMORA_DEL_CHOFER',
  HOME_ISSUE: 'PROBLEMA_CON_EL_DOMICILIO',
  PATIENT_ISSUE: 'PROBLEMA_CON_EL_PACIENTE',
  EMERGENCY: 'EMERGENCIA',
  OTHER: 'OTRO',
} as const

export type IncidentType = (typeof IncidentType)[keyof typeof IncidentType]
